FROM balenalib/amd64-node:14

# Install dependencies
RUN install_packages git jq wget
RUN wget -q https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
RUN npm install --global versionist balena-versionist
